os: Visual Studio 2017
branches:
  only:
    - master
    - test

environment:
  matrix:
    - COMPILER: msvc
      GENERATOR: Visual Studio 15 2017 Win64
      PLATFORM: x64
      BUILD_TYPE: Debug

    - COMPILER: msvc
      GENERATOR: Visual Studio 15 2017 Win64
      PLATFORM: x64
      BUILD_TYPE: Release

    - COMPILER: msvc
      GENERATOR: Visual Studio 15 2017
      PLATFORM: Win32
      BUILD_TYPE: Debug

    - COMPILER: msvc
      GENERATOR: Visual Studio 15 2017
      PLATFORM: Win32
      BUILD_TYPE: Release

install:
  - git submodule -q update --init --recursive
  - vcpkg install expat:x86-windows-static
  - vcpkg install expat:x64-windows-static
  - cd c:\tools\vcpkg
  - vcpkg integrate install

cache:
  - c:\tools\vcpkg\installed\

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - md build
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE="%BUILD_TYPE%" -DCMAKE_SH=CMAKE_SH-NOTFOUND -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\efyj ..
  - cmake --build . --config "%BUILD_TYPE%"
  - cmake --build . --config "%BUILD_TYPE%" install
  - ctest --output-on-failure --verbose -C "%BUILD_TYPE%"

after_build:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: 7z a efyj-%COMPILER%-%PLATFORM%-%BUILD_TYPE%.zip efyj

artifacts:
  - path: efyj-%COMPILER%-%PLATFORM%-%BUILD_TYPE%.zip
    name: app
