name: MacOS

on:
  push:
    branches: [ master, test, macos ]
  pull_request:
    branches: [ master, test, macos ]

env:
  CC: clang
  CXX: clang++

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        BUILD_TYPE: [Debug, Release]

    steps:
    - name: Checkout repository and submodule
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: brew install expat fmt

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --rerun-failed --output-on-failure
