name: Windows

on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master, test ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        BUILD_TYPE: [Debug, Release]

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Restore from cache and install vcpkg
      uses: lukka/run-vcpkg@v6
      with:
        setupOnly: true
    - run: |
        $VCPKG_ROOT/vcpkg install expat:windows-x64

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --rerun-failed --output-on-failure
      
