name: Windows

on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master, test ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
	BUILD_TYPE: [Debug, Release]

    steps:
      - name: Checkout repository and submodules
	uses: actions/checkout@v4
	with:
	  submodules: recursive

      - name: Install cmake
        uses: lukka/get-cmake@latest

      - name: Prepare vcpkg
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi-vcpkg'
          configurePresetAdditionalArgs: "['-DCMAKE_CXX_STANDARD=17']"
          buildPreset: 'ninja-multi-vcpkg'
          buildPresetAdditionalArgs: "['--config Release']"
          testPreset: 'ninja-multi-vcpkg'
          testPresetAdditionalArgs: "['--config Release']"
